#!/bin/bash 


memUTarget=125
wpoint="accMem"
# expected value  ->  actual value
# 	40 	  -> 	   60
# 	50 	  -> 	   70
# 	60 	  ->       80
# 	70 	  -> 	   90
# 	80 	  -> 	  100 
#      100 	  -> 	  120
#      120     	  ->      140
#      140        ->      150
# The actual constrain needs to be smaller than expected constrain.
# Because the system always doesn't react to changes of memU in time
nrround=5
expTime=720
nrlevel=5
export LD_LIBRARY_PATH=/usr/lib
swapoff -a
swapon -a
echo 3 > /proc/sys/vm/drop_caches

#begin=`date +%s`
#diff=0
#
#    Initialization
#test -e memU && rm -f memU 
#test -e etime && rm -f etime

#./genPattern 0 80 10 >> memU  		# output memUsage pattern
#./genPattern 1 0.1 0.05 >> etime 	# output Execution Time pattern
iter=0
echo hi


#arr[1]=160398 // 35%
#arr[1]=164981 // 36%
#arr[1]=166356 // 36.3%
#arr[1]=166012 // 36.225
#arr[1]=165897 // 36.20
#arr[1]=165806 // 36.18
#arr[1]=445644 // 97
#arr[1]=165500 // 75
#arr[1]=262144/297882/311630/302465 // 100
#arr[1]=412452/389538/394121 // 125

#arr[1]=165500
#arr[2]=302465
arr[1]=612452
arr[2]=412452
arr[3]=412452

#arr[1]=49152
#arr[2]=98304
#arr[3]=147456
#arr[4]=196608
#arr[5]=245760
#arr[6]=294912
#arr[7]=344064
#arr[8]=393216
#arr[9]=442368
#arr[10]=491520
#arr[11]=540672
#arr[12]=589824
#arr[13]=638976
#arr[14]=688128
#arr[15]=737280



trap trapContrC INT
function trapContrC(){
	for id in `pidof $wpoint`
	do
		kill $id
	done
	exit
	
	sarpid=`pidof sar`
	getRPSpid=`pidof getRPS`

	kill $sarpid
	kill $getRPSpid			
}

function obtainCurmemU(){

	curFree=`cat /proc/meminfo | awk '$1=="MemFree:"{print $2}'`
	curTotal=`cat /proc/meminfo | awk '$1=="MemTotal:"{print $2}'`
	curSwapFree=`cat /proc/meminfo | awk '$1=="SwapFree:"{print $2}'`
	curSwapTotal=`cat /proc/meminfo | awk '$1=="SwapTotal:"{print $2}'`
	curSwapUsage=$(($curSwapTotal-$curSwapFree))
	curUsage=$(($curTotal-$curFree+$curSwapUsage))
	curmemU=$(($curUsage*100/$curTotal))
	memUdiff=$(($memUTarget-$curmemU))

}

function calc() { awk "BEGIN{print $*}"; }     # set float arithmetic function
echo "begin"
#
#
#: ' 
#function begin()
#{
tempsum=0
count=0
function initMain(){

	sar -b -t 3 240 >> ../output/MEM_IOPS.$i & 
	/root/DYNAMIC2017/ExperimentI/Proc/nonShared/Tools/getRPS 720 &	
}
function begin_to_exper(){

	initMain
	expTime=10
	for i in $(seq 1 15)
	do
		#echo ${arr[$i]} memUTarget	
	
		begin=`date +%s`
		diff=0
		tempsum=0
		count=0
		echo $i
		while [ "$diff" -le "$expTime" ]
		do
			obtainCurmemU
			#tempsum=$((curmemU+tempsum))
			#count=$((count +1 ))
#			echo $tempsum $count

#			echo $curmemU

			while [ "$curUsage" -lt "${arr[$i]}" ]
		#	while [ "$curmemU" -lt "$memUTarget" ]
			do
				obtainCurmemU
		
#				echo "$curmemU ${arr[$i]}"
				if [ "$curUsage" -lt "${arr[$i]}" ]; then
					./$wpoint >> ../output/MEM_RTIME &
				fi
			done

			end=`date +%s`
			diff=$((end-begin))

		done
		#memUTarget ="${arr[$i]}"
		#echo $memUTarget
		#echo $tempsum $count
	done	

}

for i in $(seq 1 1)
do
	begin_to_exper $i
done

for id in `pidof $wpoint`
do
	kill $id
done
	
sarpid=`pidof sar`
getRPSpid=`pidof getRPS`

kill $sarpid
kill $getRPSpid			
