#!/bin/bash

diff=0
while [ "$diff" -le "240" ]
do
	echo $diff > /root/LMAProj2016/ExperimentI/Proc/nonShared/DiskBound/tmp/curNR
	for i in $(pgrep accDisk)
	do	
		kill -1 $i			
	done
	diff=$((diff+1))

	sleep 3
done

mv result/IO.RTIME result/IO.RTIME.$1
touch result/IO.RTIME
