#!/bin/bash 

	wpoint="accDisk"
	begin=6
	trap trapContrC INT

	function trapContrC(){
		for id in `pidof $wpoint`
		do
			echo $id
			kill $id
		done
		exit
	}
	function initMem(){
		echo 3 > /proc/sys/vm/drop_caches	
	}

	function experiment()
	{
		expTime=1000
		sum=0
		begin=`(date +%s)`
	
		initMem
		while [ "$sum" -le "$expTime" ] 	
		do
			./$wpoint &
			sleep 0.5
			end=`(date +%s)`
			sum=$(($end-$begin))
		done
	#	echo "parameter #1: $1" >> none.$1
	########## kill additional tasks #######
		for id in `pidof accDisk`
		do
			echo $id
			kill $id
		done
	########################################
	##########  release some memUsage in disk i/o #######
	#	initMem
	#####################################################
	}

	for i in $(seq $begin 7)	
	do
		experiment $i
		sleep 10
	done

