#!/bin/bash 

Main=ddworker_v2
req_start=`cat /sys/block/xvda/xvda2/stat | awk '{print $1"+"$5}'| bc`
diff=0
sum=0
count=0
export LD_LIBRARY_PATH=/usr/lib

trap trapContrC INT
function trapContrC(){
		
	
	ddworkpid=$(pidof -x "ddworker_v2")
	getMEMUpid=$(pidof -x "getMEMU_IO")
	sarpid=`pidof sar`
	iostatpid=$(pidof iostat)
	vmstatpid=$(pidof vmstat)

	kill -9 $ddworkpid
	kill -9 $sarpid
	kill -9 $iostatpid
	kill -9 $vmstatpid
	kill -9 $getMEMUpid

	exit	
}

function killMain(){
	echo "begin to kill main script"
	
	ddworkpid=$(pidof -x "ddworker_v2")
	getMEMUpid=$(pidof -x "getMEMU_IO")
	vmstatpid=$(pidof vmstat)
	iostatpid=$(pidof iostat)
	
	kill -9 $ddworkpid
	kill -9 $iostatpid
	kill -9 $vmstatpid
	kill -9 $getMEMUpid
	echo "The killing process is finished"
}
function initMain(){
	echo 3 > /proc/sys/vm/drop_caches	
	swapoff -a
	swapon -a
	
	sar -b -t 6 160 >> ../output/IO_IOPS.$1 & 
	#vmstat 6 160 >> ../output/IO_memUsage.$1 &
	iostat -x 6 160 >> ../output/IO_RPS.$1 &
	../Tools/getMEMU_IO 960 $1 &
	./$Main $1 $2 &
	
}


function Experiment(){
	#expTime=101
	expTime=960
	initMain $1 $expTime
	count=0	
	sum=0
	begin=`(date +%s)`
	tempest=$i
	req_start=`cat /sys/block/xvda/xvda2/stat | awk '{print $1"+"$5}'| bc`
	while [ "$sum" -le "$expTime" ]
	do
		
		sleep 1
		end=`date +%s`
		sum=$((end-begin))
	done
	
	killMain
}


	for i in $(seq 1 1)	
	do
		echo $i
		Experiment $i
		#nc -l 2389 && echo "i received"
	done


