#!/bin/bash 


wpoint="FixedAccMem"

nrround=5
enable_test_CAGMA=0
export LD_LIBRARY_PATH=/usr/lib


arrvm1[1]=2
arrvm1[2]=2
arrvm1[3]=2
arrvm1[4]=10
arrvm1[5]=10
######################### Additional
arrvm1[6]=10


iter=0

echo 3 > /proc/sys/vm/drop_caches
trap trapContrC INT
function trapContrC(){
	

	for id in $(pidof $wpoint)
	do
		kill -9 $id
	done

	sarpid=$(pidof sar)
	kill -9 $sarpid
	
	rmmod supCenter.ko
	rmmod resetCMA.ko
	rmmod MemDataCollector.ko
	exit	
}
function killWpoint(){
	
	for id in $(pidof $wpoint)
	do
		kill -9 $id
	done

}
function killMain(){
	

	killWpoint	
	sarpid=$(pidof sar)
	kill -9 $sarpid
}
function getNRmainProg(){
	
	NRmainProg=0
	
	for i in $(pidof FixedAccMem)
	do
		NRmainProg=$((NRmainProg+1))	
	done 
}


function calc() { awk "BEGIN{print $*}"; }     # set float arithmetic function
echo "begin"

tempsum=0
count=0
function initMain(){

	swapoff -a
	swapon -a
}

function wait_for_(){	

	ret=1
	echo "I send a packet to controller"
	while [ "$ret" == "1" ]
	do
		echo hi | nc 203.64.125.101 2391 
		ret=`echo $?`	

	done
	
	while [ "$ret" != "hi" ]
	do	
		ret=$(nc -l 2390)
	done
	echo "VM1: i received a packet, ans: $ret"

}

function wait_for_testing_CMA(){	

	ret=1
	echo "I send a packet to controller"
	while [ "$ret" == "1" ]
	do
		echo hi | nc 203.64.125.101 2394
		ret=`echo $?`	
	done

	while [ "$ret" != "hi" ]
	do	
		ret=$(nc -l 2390)
	done
	echo "VM1: i received a packet for CMA, ans: $ret"

}

function begin_to_exper(){

	
	wait_for_	


	initMain 
	
	expTime=60
	spoint=0
	prev=0
		
	sar -b -t 3 110  >> ./result/MEM_IOPS.$1 & 
	./FileSuffexSetter $1
	
	for i in $(seq 1 6)
	do
	
		temest=${arrvm1[$i]}

		diff=0
		
		result=$((temest-prev))

		for j in $(seq 1 $result)
		do
			./$wpoint $spoint &
		done
		

		prev=$temest
		echo "enter $i/10, ans = $temest"	
		
		begin=`date +%s`
		while [ "$diff" -le "$expTime" ]
		do
			NRmainProg=`pgrep FixedAccMem | wc -l`
			if [ "$NRmainProg" -lt "$temest" ]; then	
				 ./$wpoint  &
			fi

			end=`date +%s`
			diff=$((end-begin))
		done
	
	done
}

for i in $(seq 1 20)
do
	if [ "$enable_test_CAGMA" -eq "1" ]; then
		insmod ../Tools/resetCMA/resetCMA.ko 
		rmmod resetCMA.ko
		echo "reset CMA.........done"
		insmod /root/LMAProj2016/supCenter/supCenter.ko 
		echo "install supCenter.........done"	
	fi

	echo $i
	insmod ./monitor/MemDataCollector.ko
	begin_to_exper $i
	
	NRmainProg=`pgrep FixedAccMem | wc -l`
	while [ "$NRmainProg" -gt "0" ];
	do
		killWpoint
		NRmainProg=`pgrep FixedAccMem | wc -l`
	done
	
	echo "waitfor iops"
	sleep 10	
	echo "waitfor iops......done"
	rmmod MemDataCollector.ko

	if [ "$enable_test_CAGMA" -eq "1" ]; then
		
		rmmod supCenter.ko
		echo "uninstall supCenter.........done"
		
		wait_for_testing_CMA
		echo "I'm ready to test next CAGMA"
	else
		wait_for_	
	fi

done


