#!/bin/bash 


wpoint="FixedAccMem"
# expected value  ->  actual value
# 	40 	  -> 	   60
# 	50 	  -> 	   70
# 	60 	  ->       80
# 	70 	  -> 	   90
# 	80 	  -> 	  100 
#      100 	  -> 	  120
#      120     	  ->      140
#      140        ->      150
# The actual constrain needs to be smaller than expected constrain.
# Because the system always doesn't react to changes of memU in time
nrround=5
enable_test_CAGMA=0
expTime=720
nrlevel=5
export LD_LIBRARY_PATH=/usr/lib

#begin=`date +%s`
#diff=0
#
#    Initialization
#test -e memU && rm -f memU 
#test -e etime && rm -f etime

#./genPattern 0 80 10 >> memU  		# output memUsage pattern
#./genPattern 1 0.1 0.05 >> etime 	# output Execution Time pattern




arrvm2[1]=2
arrvm2[2]=2
arrvm2[3]=2
arrvm2[4]=9
arrvm2[5]=9
arrvm2[6]=9
arrvm2[7]=9
arrvm2[8]=9
arrvm2[9]=9
############Additional
arrvm2[10]=9
iter=0

echo 3 > /proc/sys/vm/drop_caches
trap trapContrC INT
function trapContrC(){
	

	for id in $(pidof $wpoint)
	do
		kill -9 $id
	done

	sarpid=$(pidof sar)
	DCollector=$(pidof -x DataCollector)
	kill -9 $DCollector	
	kill -9 $sarpid
	
	rmmod MemNotifier.ko
	rmmod supCenter.ko
	rmmod resetCMA.ko
	exit	
}
function killWpoint(){
	
	for id in $(pidof $wpoint)
	do
		kill -9 $id
	done

}
function killMain(){
	

	killWpoint	
	sarpid=$(pidof sar)	
	DCollector=$(pidof -x DataCollector)
	kill -9 $DCollector	
	kill -9 $sarpid
}
function getNRmainProg(){
	
	NRmainProg=0
	
	for i in $(pidof FixedAccMem)
	do
		NRmainProg=$((NRmainProg+1))	
	done 
}

function obtainCurmemU(){

	curFree=`cat /proc/meminfo | awk '$1=="MemFree:"{print $2}'`
	curTotal=`cat /proc/meminfo | awk '$1=="MemTotal:"{print $2}'`
	curSwapFree=`cat /proc/meminfo | awk '$1=="SwapFree:"{print $2}'`
	curSwapTotal=`cat /proc/meminfo | awk '$1=="SwapTotal:"{print $2}'`
	curSwapUsage=$(($curSwapTotal-$curSwapFree))
	curUsage=$(($curTotal-$curFree+$curSwapUsage))
	curmemU=$(($curUsage*100/$curTotal))
	memUdiff=$(($memUTarget-$curmemU))

}

function calc() { awk "BEGIN{print $*}"; }     # set float arithmetic function
echo "begin"
#
#
#: ' 
#function begin()
#{
tempsum=0
count=0
function initMain(){

	swapoff -a
	swapon -a
	#echo 0 > /proc/sys/vm/drop_caches
	#iostat -x 3 240 >> ../output/MEM_RPS.$1 &
	#vmstat 6 160 >> ../output/MEM_memUsage.$1 &
	#../Tools/getMEMU_MEM 960 $1 &	
}

function wait_for_(){	

	ret=1
	echo "I send a packet to controller"
	while [ "$ret" == "1" ]
	do
		echo hi | nc 203.64.125.101 2392
		ret=`echo $?`	
	done
	
	while [ "$ret" != "hi" ]
	do	
		ret=$(nc -l 2390)
	done
	echo "VM2: i received a packet, ans=$ret"
}

function wait_for_testing_CMA(){	

	ret=1
	echo "I send a packet to controller"
	while [ "$ret" == "1" ]
	do
		echo hi | nc 203.64.125.101 2395
		ret=`echo $?`	
	done
	
	while [ "$ret" != "hi" ]
	do	
		ret=$(nc -l 2390)
	done
	echo "VM2: i received a packet for CMA, ans=$ret"
}



function begin_to_exper(){

	
	wait_for_

	initMain
	expTime=60
	prev=0

	sar -b -t 3 110 >> ./result/MEM_IOPS.$1 & 	
	./GameGate $1

	for i in $(seq 1 6)
	do	

		begin=`date +%s`
		temest=${arrvm2[$i]}
		diff=0
		
		result=$((temest-prev))
		for j in $(seq 1 $result)
		do
			./$wpoint  &
		done
		prev=$temest
		echo "enter $i/5, nrtask: $temest"
	
		while [ "$diff" -le "$expTime" ]
		do
			end=`date +%s`
			diff=$((end-begin))
		done
	done
}

for i in $(seq 1 20)
do
	if [ "$enable_test_CAGMA" -eq "1" ]; then
		insmod ../Tools/resetCMA/resetCMA.ko 
		rmmod resetCMA.ko
		echo "reset CMA.........done"
		insmod /root/LMAProj2016/supCenter/supCenter.ko 
		echo "install supCenter.........done"	
	fi
 	
	
	echo $i
	insmod ./monitor/MemNotifier.ko
	begin_to_exper $i
	
	echo "killing $wpoint process"
	NRmainProg=`pgrep FixedAccMem | wc -l`
	while [ "$NRmainProg" -gt "0" ];
	do
		killWpoint
		NRmainProg=`pgrep FixedAccMem | wc -l`
	done
	echo "killing is done"

	
	echo "waitfor iops"
	sleep 10	
	echo "waitfor iops......done"
	rmmod MemNotifier.ko



	if [ "$enable_test_CAGMA" -eq "1" ]; then
		rmmod supCenter.ko

		echo "uninstall supCenter.........done"
		wait_for_testing_CMA	
		echo "I'm ready to test next CAGMA"
		
	else
		wait_for_
	fi

done


