#!/bin/bash



for i in $(seq 0 39)
do
#	ans=`echo $i%2 | bc`
#	if [ "$ans" == "0" ]; then
#		xl mem-set Domain-0 512
#		xl mem-set Domain-0 1024
#		echo "reset domain-0"
#	fi

		
	xl mem-set vm1 512 && xl mem-set vm2 512 && xl mem-set vm3 512
	xl mem-max vm1 2500 && xl mem-max vm2 2500 && xl mem-max vm3 2500
#	xl mem-set vm1 512 && xl mem-set vm3 512
#	xl mem-max vm1 2500 && xl mem-max vm3 2500

	nc -l 2391 && echo "vm1 is ready to run"
	nc -l 2392 && echo "vm2 is ready to run"
	nc -l 2393 && echo "vm3 is ready to run"

	 

	sleep 5
	echo "ready to sync all vms"
	ret1=1
	ret2=1
	ret3=1

	while [ "$ret1" == "1" ] || [ "$ret2" == "1" ] || [ "$ret3" == "1" ]
 # 	while [ "$ret1" == "1" ] || [ "$ret3" == "1" ]
   	do
      		sleep 1
       		echo "I send a packet to other"
       		echo hi | nc 203.64.125.27 2390
       		ret1=`echo $?`    	
       		echo hi | nc 203.64.125.66 2390 
      		ret2=`echo $?`    
		echo hi | nc 203.64.125.28 2390 
       		ret3=`echo $?`    
   	done	
	echo "i got it"	

done


