#!/bin/bash


# The round of synchronization is 2 x the number of rounds in Task Generator 
# due to that each round in Task Generator needs two times of synchronization: 1
# One is synchronization at the beginning of each round in Task Generator
# Another one is synchronization at the end of each round in Task Generator

# For example, if the number of rounds in Task Generator is 5, then the round
# of synchronization is 5x2 or 10
# set the maximum number of rounds of synchronization
NRround=10

# to synchronize Task Generator in each VM for each round
for i in $(seq 1 $NRround)
do
	# set three listeners to wait to receive data for each VM
	nc -l 2391 && echo "vm1 is ready to run"
	nc -l 2392 && echo "vm2 is ready to run"
	nc -l 2393 && echo "vm3 is ready to run"

	# synchronize
	sleep 5

	echo "ready to sync all vms"
	
	# initialize 
	ret1=1 		#VM1
	ret2=1 		#VM2
	ret3=1 		#VM3
	msg="none"

	# each VM waits for each other until the simulator successfully
	# receives the data for each VM
	while [ "$msg" != "hi" ]
   	do
		# waits until each VM receive the packet
      		if [ "$ret1" -eq "0" ] && [ "$ret2" -eq "0" ] && [ "$ret3" -eq "0" ]; then
			msg="hi"
		fi

		# each VM also set a listener to sync 
		echo $msg | nc 203.64.125.27 2390 	# send a packet to VM1
       		ret1=`echo $?`    			# When VM1 receives the packet, it returns 0	
       		echo $msg | nc 203.64.125.66 2390 	# send a packet to VM2
       		ret2=`echo $?`   			# When VM2 receives the packet, it returns 0
		echo $msg | nc 203.64.125.28 2390 	# send a packet to VM3
       		ret3=`echo $?`   			# When VM3 receives the packet, it returns 0 

	done

done


