#!/bin/bash

diff=0
while [ "$diff" -le "240" ]
do
	echo $diff > /root/LMAProj2016/ExperimentI/Proc/nonShared/MemBound/tmp/curNR
	for i in $(pgrep FixedAccMem)
	do	
		kill -1 $i			
	done
	diff=$((diff+1))

	sleep 3
done

mv result/MEM.RTIME result/MEM.RTIME.$1
touch result/MEM.RTIME
